### ISSUE TITLE
Deployment Error: No stacks match the name(s) SdfHubWorkflowStack

### ISSUE THREAD

**Issue by sathish0804** [aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws#10]
I encountered an error while trying to seed the SIF impact factor resources and execute the `ghg:scope_3:purchased_goods_and_services` pipeline. The command I ran is:

`npm run cdk -- deploy -c hubAccountId=<HUB_ACCOUNT_ID> \
-c spokeAccountId=<SPOKE_ACCOUNT_ID> -c domainId=<DATAZONE_DOMAIN_ID> \
-c domainName=<DATAZONE_DOMAIN_NAME> -c projectId=<DATAZONE_PROJECT_ID> \
-c athenaEnvironmentId=<DATAZONE_DATA_LAKE_ENV_ID> -c redshiftEnvironmentId=<DATAZONE_DATA_WAREHOUSE_ENV_ID> \
-c roleArn=<SERVICE_ROLE_ARN> -c environment=<SIF_ENV> -c tenantId=<SIF_TENANT_ID> \
-c sifAdminEmailAddress=<SIF_ADMIN_EMAIL> -c sdfAdminUserId=<IAM_IDENTITY_CENTER_USERNAME> \
—require-approval never —concurrency=10 SdfHubWorkflowStack
`

**Error Message**
After running the command, I received the following error:
No stacks match the name(s) SdfHubWorkflowStack

**Comment by johnrotach** [comment]
My apologies for this, this is a typo in our instructions. The stack name is: `SdfSpokeWorkflowStack`. Thanks for reporting this. I'll make sure we get a ticket in to update the docs.
