### ISSUE TITLE
High Costs Associated with SageMaker Usage and Inquiry About Service Pausing

### ISSUE THREAD

**Issue by sathish0804** [aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws#12]
![image](https://github.com/user-attachments/assets/82f08595-6a38-493b-9f47-61e9fcd3879e)
### Description
I have deployed the solution from the [sustainability data fabric on AWS](https://github.com/aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws) repository and have some questions regarding the services being utilized.

### Questions
1. **Purpose of Using SageMaker:**
   - Could you please clarify why SageMaker is integrated into this architecture? What specific functionalities or advantages does it provide in the context of sustainability data processing?

2. **Cost Management:**
   - I have noticed that several services, including SageMaker, are incurring significant costs. Are there any recommendations for optimizing costs associated with these services? 

3. **Pausing Services:**
   - After deployment, is it possible to pause or stop these services if we are not actively using them? What are the best practices for managing these resources to avoid unnecessary charges during periods of inactivity?

Thank you for your assistance!

**Comment by johnrotach** [comment]
I think first some basic guidance on DF, SDF, and SIF and the functions of each will help make decisions on what services you may or may not require in your solution.

* [SIF](https://github.com/aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework) - The Sustainability Insights Framework guidance contains microservices which help build a carbon accounting solution on AWS. These microservices implement common building blocks of carbon accounting such as an emissions factor catalog (called impacts in SIF), reusable calculations, and management and orchestration of activity processing pipelines. The intention of this guidance is to provide a starting point for someone who wanted to implement their own carbon accounting solution on AWS. There are integrations into DF which allow SIF to act as a data product in the fabric and consume and produce assets from and to the fabric. *Note*: See side note about SageMaker below.
* [DF](https://github.com/aws-solutions-library-samples/guidance-for-data-fabric-on-aws) - Building a Data Fabric on AWS guidance is meant to be an accelerator for customer wishing to implement a data fabric type architecture on AWS using DataZone and services such as AWS Glue. The guidance provides an API which orchestrates the common pillars of a data fabric such as business metadata, data quality, and data lineage. These are the two hub and spoke step functions which are deployed in the guidance. This guidance is meant to be used by a data product which is publishing data assets into the data fabric. In a Data Fabric approach a data product is owned by a team in an organization. They own their own data and make it available to other groups in the organization through a mechanism such as an API or a central data repository. The Data Fabric guidance is meant to be independent of verticals (such as manufacturing or sustainability).
* [SDF](https://github.com/aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws) - Building a Sustainability Data Fabric on AWS guidance is a "view" or an application of the above Data Fabric guidance in the sustainability space. It is meant to be a guide of how someone could possibly apply the Data Fabric guidance to the sustainability space. It isn't the intention that this guidance deployment is long-lived and used as a solution. It instead is meant to be a guide to illustrate the concepts of the DF guidance and then torn down after gathering learning to implement your own approach. When deploying the SDF guidance it uses SIF to consume and produce data products in DF. See [here](https://github.com/aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws/tree/main/typescript/packages/demo) for documentation on the flow.

**SageMaker in SIF:** SageMaker is used in SIF to implement CaML (https://www.amazon.science/publications/caml-carbon-footprinting-of-household-products-with-zero-shot-semantic-text-similarity) for matching products to their economic sector to aid in Economic Input-Output based Life Cycle Assessments (EIO-LCA). See [here](https://github.com/aws-solutions-library-samples/guidance-for-aws-sustainability-insights-framework/blob/main/typescript/packages/apps/pipelines/docs/pipeline-caml.md) for a walkthrough of the CaML pipeline type. This may be a feature you won't require in your solution. The SDF guidance makes use of the CaML feature to demonstrate taking product data and creating impact factors which are then put in the data fabric. See [here](https://github.com/aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws/tree/main/typescript/packages/demo) for the SDF flow and where CaML is used.

Given all of the above you are free to use the SageMaker service as you see fit. If you do not need the CaML functionality, you can deploy SIF without setting the caml deployment options and the SageMaker infrastructure will not be deployed. You can also deploy the DF guidance and not deploy SIF or SDF.
