### ISSUE TITLE
Clarification Needed on Deployment Steps for SIF Framework

### ISSUE THREAD

**Issue by sathish0804** [aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws#6]
![image](https://github.com/user-attachments/assets/da40a74c-5465-464a-982a-63670a76ff39)

I am working on deploying the Guidance for AWS Sustainability Data Fabric and have followed the steps as mentioned in the documentation. However, I encountered some confusion and need clarification to ensure I’m proceeding correctly.

### In the third step,
Deploy the Guidance for Sustainability Insights Framework sample code. See steps 
![image](https://github.com/user-attachments/assets/c23ae44b-6535-4e00-b562-4106930a4408)
Do I need to complete these steps first? After completing these steps, do I need to proceed further with the deployment of Guidance for AWS Sustainability Data Fabric?

**Comment by johnrotach** [comment]
Yep, you will have to deploy the SIF guidance code and then go back to the SDF install. The SDF install relies on SIF to be deploy as it seeds resources (impact factors, pipelines, etc) into SIF and then runs the pipelines.

**Comment by sathish0804** [comment]
![image](https://github.com/user-attachments/assets/bd6bc6ce-2433-44b9-b5ab-eb1e6ec35ea8)

for SIF deployment do i need to use use Hub account or Spoke account

**Comment by johnrotach** [comment]
Ahhh yes. SIF would be deployed in the spoke account.
