### ISSUE TITLE
Clarification Needed on Deployment Steps 3.1 to 3.10

### ISSUE THREAD

**Issue by sathish0804** [aws-solutions-library-samples/guidance-for-building-a-sustainability-data-fabric-on-aws#8]
Hello,
I have successfully deployed step 3 of the Sustainability Data Fabric (i,e SIF)
![image](https://github.com/user-attachments/assets/6b05c4a6-73cf-4183-8b90-afc4268a7c13)
After this deployment, Do I need to deploy all of the steps from 3.1 to 3.10 after deploying step 3

**Comment by johnrotach** [comment]
Steps 3.1 - 3.10 in this repo are meant to be instructions on deploying SIF. If you have done this from the SIF repo instructions you should not need to repeat them.

**Comment by sathish0804** [comment]
I done with SIF, but in that i didnot used this command `npm run cdk -- deploy -c tenantId=<tenantId> -c environment=<SIF_ENVIRONMENT> -c administratorEmail=<ADMIN_EMAIL> \
 -c enableDeleteResource=true -c deleteBucket=true -c includeCaml=true \
 -c idcEmail=<idcEmail> -c idcUserId=<idcUserId> -c dfSustainabilityRoleArn=<dfSustainabilityRoleArn> \
 -c dataFabricRegion=<dataFabricRegion> -c dataFabricEventBusArn=<dataFabricEventBusArn> \
 --all --require-approval never --concurrency=10`
in that repo (SIF repo) the command is different
![image](https://github.com/user-attachments/assets/d881df74-e0b6-4436-825b-df3e7815e77f)
can i delete all the stacks related to sif and can i run 
![image](https://github.com/user-attachments/assets/1905ee74-fe6d-4fbc-b5f5-599fd64e5d97)
or is there any solution without deleting the sif stacks

**Comment by johnrotach** [comment]
Ahhh, I understand your question now. Thanks. You _should_ be able to deploy SIF with those commands w/o having to delete the stacks but I'm not sure this flow has been tested. I would try to deploy without deleting and if you run into any issues it shouldn't take too long to destroy the SIF stacks and start fresh.

**Comment by sathish0804** [comment]
![image](https://github.com/user-attachments/assets/d0fe302d-5b25-4492-925c-27ff23291445)

while running the 3.7 command, iam getting this error
`Failed resources:sif-shared-dev-platform | 12:00:26 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource           | Networks3LogBucketAutoDeleteObjectsCustomResource67149C79 Received response status [FAILED] from custom resource. Message returned: AccessDenied: User: arn:aws:sts::127214185556:assumed-role/sif-shared-dev-platform-CustomS3AutoDeleteObjectsCu-vE7s9FHH7P8x/sif-shared-dev-platform-CustomS3AutoDeleteObjectsC-pk8FnswmNaOi is not authorized to perform: s3:GetBucketTagging on resource: "arn:aws:s3:::sif-vpc-logs-dev-127214185556-us-east-1" because no identity-based policy allows the s3:GetBucketTagging action    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:840:20)    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:849:5    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4749:14)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22 (RequestId: 6093c5eb-217e-49ae-ab9c-b308526d735d)sif-shared-dev-platform | 12:00:27 PM | DELETE_FAILED        | AWS::CloudFormation::CustomResource           | Networks3AccessLogAutoDeleteObjectsCustomResource457D972E Received response status [FAILED] from custom resource. Message returned: AccessDenied: User: arn:aws:sts::127214185556:assumed-role/sif-shared-dev-platform-CustomS3AutoDeleteObjectsCu-vE7s9FHH7P8x/sif-shared-dev-platform-CustomS3AutoDeleteObjectsC-pk8FnswmNaOi is not authorized to perform: s3:GetBucketTagging on resource: "arn:aws:s3:::sif-access-logs-dev-127214185556-us-east-1" because no identity-based policy allows the s3:GetBucketTagging action    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:840:20)    at /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/smithy-client/dist-cjs/index.js:849:5    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4749:14)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:482:18    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22    at async /var/runtime/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22 (RequestId: 06a0f599-493f-4bf3-bb0f-195ca3aa788a)`
but stack has deployed successfully.
If i delete all the SIF stacks, will it removes all iam roles and services associated with the SIF
